### PR TITLE
fix when used under perl 5.26.

### PR DESCRIPTION
**Pull request by gugod**
The field "op_sibling" was removed in 5.26 and replaced by another
field "op_sibparent" that is a joint pointer to either the next
sibiling or parent if there is no next sibling.

See perl5.git commit 86cd3a13b6713cc9d8406c9316fe126788e2497f

### CODE REVIEW

**Comment by lukec** [comment]
Glorious!

**Comment by gugod** [comment]
@clkao, @audreyt,

are you guys availble to release this change to CPAN ? If not, could you grant @lukec and/or me comaint bit so it can be done ? :)

**Comment by audreyt** [comment]
Just checked PAUSE and I don't have a commit bit... Seems @clkao is the maintainer

**Comment by clkao** [comment]
@gugod @lukec you are now both co-maint.

**Comment by gugod** [comment]
@clkao thanks 👍

**Pull request merged**
